### PR TITLE
Example import problem

### PR DESCRIPTION
**Pull request by felixmosh**
This is a PR which fixes the mangling error, it just uses the default optimization settings

### CODE REVIEW

**Comment by vladnicula** [comment]
@felixmosh thank you so much for taking the time on this. I'm really happy to have another set of eyes on this. 

As I've stated in the comments in the StackOverflow question, I need to use mangling in the production code. Removing Terser is not an option unless I use another solution for code mangling.

**Comment by felixmosh** [comment]
But the default setup minifies (mangling) the bundle as well...

**Comment by vladnicula** [comment]
It does not. For example, we can still find in the bundle code the method `doAjaxCall` with that name https://github.com/vladnicula/terser-for-the-win/blob/4165a382c3fac63d87fb7d49d4de9aca4b599217/src/app.ts#L13

With terser, `doAjaxCall` becomes `_x` or something cryptic like that.

**Comment by vladnicula** [comment]
wait, no, you might be right!!! :O

**Comment by vladnicula** [comment]
```js
!function(){"use strict";var t,o={903:function(t,o,e){Object.defineProperty(o,"__esModule",{value:!0}),o.App=void 0;var n=e(876),i=function(){function t(){}return t.prototype.init=function(){var t=this;console.log(n.default);var o=n.default("title").first();console.log("extrected with jQuery: ",o.text().trim()),setTimeout((function(){t.doAjaxCall()}),100)},t.prototype.doAjaxCall=function(){console.log("example payload that is not mangled",{shop_id:"someId",beep:"boop"})},t}();o.App=i},876:function(t){t.exports={default:window.jQuery}}},e={};t=function t(n){var i=e[n];if(void 0!==i)return i.exports;var r=e[n]={exports:{}};return o[n](r,r.exports,t),r.exports}(903),window.APP_SCOPE={init:function(){(new t.App).init()}},window.APP_SCOPE.init()}();
```

This is what is generated. Notice how doAjaxCall still exists in the final source code?

**Comment by felixmosh** [comment]
> ```js
> !function(){"use strict";var t,o={903:function(t,o,e){Object.defineProperty(o,"__esModule",{value:!0}),o.App=void 0;var n=e(876),i=function(){function t(){}return t.prototype.init=function(){var t=this;console.log(n.default);var o=n.default("title").first();console.log("extrected with jQuery: ",o.text().trim()),setTimeout((function(){t.doAjaxCall()}),100)},t.prototype.doAjaxCall=function(){console.log("example payload that is not mangled",{shop_id:"someId",beep:"boop"})},t}();o.App=i},876:function(t){t.exports={default:window.jQuery}}},e={};t=function t(n){var i=e[n];if(void 0!==i)return i.exports;var r=e[n]={exports:{}};return o[n](r,r.exports,t),r.exports}(903),window.APP_SCOPE={init:function(){(new t.App).init()}},window.APP_SCOPE.init()}();
> ```
> 
> This is what is generated. Notice how doAjaxCall still exists in the final source code?

Correct, since this is a property which can't (and shouldn't)  be mangled

**Pull request merged**
